---
- name: ensure php-fpm is at the latest version
  package: name=php-fpm state=latest
- name: ensure php-fpm is running (and enable it at boot)
  service: name=php-fpm state=started enabled=yes
- name: ensure nginx is at the latest version
  package: name=nginx state=latest
- name: write the nginx config file
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
  - restart nginx
- name: ensure nginx is running (and enable it at boot)
  service: name=nginx state=started enabled=yes
