---
- hosts: all
  remote_user: root
  tasks:
  - name: ensure php-fpm is at the latest version
    package: name=php-fpm state=latest
  - name: ensure php-fpm is running (and enable it at boot)
    service: name=php-fpm state=started enabled=yes
- hosts: all
  vars:
    http_port: 80
    server_name: localhost
  remote_user: root
  tasks:
  - name: ensure nginx is at the latest version
    package: name=nginx state=latest
  - name: write the nginx config file
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
    - restart nginx
  - name: write the demo index file
    copy: src=templates/index.php dest=/var/www/index.php
    notify:
    - restart nginx
  - name: ensure nginx is running (and enable it at boot)
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
- hosts: all
  remote_user: root
  tasks:
  - name: ensure mariadb is at the latest version
    package: name=mariadb state=latest
  - name: ensure mariadb is running (and enable it at boot)
    service: name=mariadb state=started enabled=yes
